"""
Modified from code generated by Claude 3.7 Sonnet
"""

import cv2
import numpy as np
from pathlib import Path


def detect_aruco_markers(input_image_path, output_image_path):
    """
    Detects ArUco markers in an image and returns their IDs and corner
    locations.
    
    Args:
        input_image_path (str): Path to the input image.
        output_image_path (str): Path to save the output image with detected
            markers.
        
    Returns:
        tuple: (total_markers, marker_ids, corner_locations)
    """
    # Read the input image
    image = cv2.imread(input_image_path)
    if image is None:
        raise FileNotFoundError(f"Could not read image: {input_image_path}")
    
    # Convert to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    
    # Define the ArUco dictionary (this requires OpenCV 4.7 and later;
    # older versions have a different API)
    aruco_dict = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_1000)
    detector = cv2.aruco.ArucoDetector(aruco_dict)
    corners, ids, rejected = detector.detectMarkers(gray)
    
    # Get total number of markers detected
    total_markers = 0 if ids is None else len(ids)
    
    # Create a list to store corner locations more readably
    corner_locations = []
    
    if total_markers > 0:
        # Convert corners to a more readable format
        for i, corner in enumerate(corners):
            # Each corner has 4 points (top-left, top-right, bottom-right,
            # bottom-left).
            # Reshape to get a 4x2 array (4 points with x, y coordinates)
            corner_points = corner.reshape((4, 2))
            corner_locations.append(corner_points)
        
        # Draw detected markers on a copy of the image for visualization
        image_with_markers = image.copy()
        cv2.aruco.drawDetectedMarkers(image_with_markers, corners, ids)
        cv2.imwrite(output_image_path, image_with_markers)
    
    return total_markers, ids, corner_locations

def process_image(input_image_path, output_image_path):
    try:
        total_markers, marker_ids, corner_locations = detect_aruco_markers(
            input_image_path, output_image_path
        )
        
        # Display results
        print(f"Total ArUco markers detected: {total_markers}")
        
        if total_markers > 0:
            print("\nArUco marker details:")
            for i in range(total_markers):
                marker_id = marker_ids[i][0]
                print(f"\nMarker ID: {marker_id}")
                print("Corner locations (x, y):")
                for j, point in enumerate(corner_locations[i]):
                    corner_name = [
                        "Top-Left", "Top-Right", "Bottom-Right", "Bottom-Left"
                    ][j]
                    print(
                        f"  {corner_name}: ({point[0]:.1f}, {point[1]:.1f})"
                    )
        
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__": 
    base_dir = Path("./output/detection_examples")
    base_dir.mkdir(parents=True, exist_ok=True)

    process_image(
        base_dir / "sample_aruco_image_0.3mm_24x22.jpg",
        base_dir / "sample_aruco_image_0.3mm_24x22_detected.jpg"
    )

    print("*" * 80)

    process_image(
        base_dir / "sample_aruco_image_0.4mm_25x17.jpg",
        base_dir / "sample_aruco_image_0.4mm_25x17_detected.jpg"
    )
