#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#include <iostream>

// Behavior camera / frame grabber
#define BEHAVIOR_CAMERA_FULL_FRAME_WIDTH 2560
#define BEHAVIOR_CAMERA_FULL_FRAME_HEIGHT 2048
#define BEHAVIOR_CAMERA_ROI_WIDTH 1984
#define BEHAVIOR_CAMERA_ROI_HEIGHT 1024
#define BEHAVIOR_CAMERA_FRAME_GRABBER_TRIGGER_LINE "TTLIO12"
#define BEHAVIOR_CAMERA_STREAMING_FPS 25
#define NUM_BEHAVIOR_IMAGE_SAVING_THREADS 4
#define BEHAVIOR_CAMERA_DEFAULT_FPS 100
#define BEHAVIOR_CAMERA_DEFAULT_EXPOSURE_TIME_MICROSECS 1000

// Motion stages
#define MOTION_STAGE_SERIAL_NUMBER_X_AXIS 133838
#define MOTION_STAGE_SERIAL_NUMBER_Y_AXIS 122390
#define MOTION_STAGE_VELOCITY_UNIT \
    zaber::motion::Units::VELOCITY_MILLIMETRES_PER_SECOND
#define MOTION_STAGE_LENGTH_UNIT \
    zaber::motion::Units::LENGTH_MILLIMETRES

// Triggering
#define BUFFER_FLUSHING_WAIT_TIME_MILLISECS 100
#define ARDUINO_BAUD_RATE_Q_ENUM QSerialPort::Baud9600
#define ARDUINO_BAUD_RATE_INT 9600
#define ARDUINO_COMM_TIMEOUT_MILLISECS 1000
#define ARDUINO_COMM_RETRIES 3

// IO
#define DEFAULT_SAVE_DIRECTORY "./images"
#define LOG_BEHAVIOR_CAMERA_SAVE_PERFORMANCE_INTERVAL 100
#define ARDUINO_DEVICE_MANUFACTURER "Arduino"
#define ARDUINO_DEVICE_DESCRIPTION "Nano ESP32"
#define MOTION_STAGE_DEVICE_MANUFACTURER "Zaber Technologies Inc."
#define MOTION_STAGE_DEVICE_DESCRIPTION "X-MCC2"

// GUI and live streaming
#define GUI_BEHAVIOR_CAMERA_PREVIEW_WIDTH 640
#define GUI_BEHAVIOR_CAMERA_PREVIEW_HEIGHT 480

#endif // CONSTANTS_HPP
