#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#include <iostream>

// Behavior camera / frame grabber
#define BEHAVIOR_CAMERA_FULL_FRAME_WIDTH 2560
#define BEHAVIOR_CAMERA_FULL_FRAME_HEIGHT 2048
#define BEHAVIOR_CAMERA_ROI_WIDTH 1984
#define BEHAVIOR_CAMERA_ROI_HEIGHT 1024
#define BEHAVIOR_CAMERA_FRAME_GRABBER_TRIGGER_LINE "TTLIO12"
#define BEHAVIOR_CAMERA_STREAMING_FPS 25
#define NUM_BEHAVIOR_IMAGE_SAVING_THREADS 4

// Motion stages
#define MOTION_STAGE_SERIAL_NUMBER_X_AXIS 133838
#define MOTION_STAGE_SERIAL_NUMBER_Y_AXIS 122390
#define MOTION_STAGE_VELOCITY_UNIT \
    zaber::motion::Units::VELOCITY_MILLIMETRES_PER_SECOND
#define MOTION_STAGE_LENGTH_UNIT \
    zaber::motion::Units::LENGTH_MILLIMETRES
#define MOTION_STAGE_SERIAL_PORT_NAME "/dev/ttyACM0"

// Triggering
#define BUFFER_FLUSHING_WAIT_TIME_MILLISECS 100

// IO
#define DEFAULT_SAVE_DIRECTORY "./images"

// GUI
#define GUI_BEHAVIOR_CAMERA_PREVIEW_WIDTH 640
#define GUI_BEHAVIOR_CAMERA_PREVIEW_HEIGHT 480

#endif // CONSTANTS_HPP
