[env:arduino_nano_esp32]
; Same platform and C++ standard as trigger_firmware/platformio.ini.
platform = espressif32 @ ^6.13.0
board = arduino_nano_esp32
framework = arduino

build_unflags =
    -std=gnu++11
    -std=gnu++14
    -std=gnu++17
build_flags =
    -std=gnu++2a

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
