import logging
import time
from subprocess import run

import tyro

import spotlight_postprocessing_scitas.common.config as config
from spotlight_postprocessing_scitas.common.db import (
    DispatcherStatus,
    JobsDatabase,
    TrialStatus,
)

logger = logging.getLogger(__name__)


def spotlight_job_dispatcher(job_id: str, poll_interval_seconds: float = 15.0) -> None:
    """Watch a postprocessing job in Firestore and dispatch each trial's pre-generated
    SLURM postprocessing job as soon as its input data has finished copying.

    Runs on a SCITAS compute node (launched by `launch_dispatcher`, which also
    pre-generates every trial's task manifest and SLURM batch script, since the job's
    trials and parameters are already known from Firestore at that point). Polls
    Firestore for trials with status `INPUT_COPIED`; for each one found, submits its
    pre-generated SLURM batch script via `sbatch` and marks it `PROCESSING_QUEUED`
    (the trial's own SLURM job later marks it `PROCESSING` once it actually starts
    running). Quits once no trial is still `WAITING_ON_INPUT_COPY` or `INPUT_COPIED`
    (i.e. every trial has at least been dispatched for processing).

    This dispatcher's own status (`RUNNING`, then `COMPLETE` or `FAILED`) is recorded
    in Firestore under the job's `dispatcher` field, alongside the SLURM job ID
    recorded by `launch_dispatcher`.

    Args:
        job_id: ID of the job (as generated by `submit_remote_postprocessing_job`) to
            dispatch.
        poll_interval_seconds: How often, in seconds, to poll Firestore for newly
            copied trials.
    """
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
    )

    db = JobsDatabase(config.FIRESTORE_SERVICE_ACCOUNT_KEY_PATH)
    job_dir = (
        config.SCITAS_EXPORT_MOUNTPOINT_SCITAS / config.SCITAS_EXPORT_RELATIVE_WORKDIR
    ).resolve() / job_id

    db.update_dispatcher_status(job_id, DispatcherStatus.RUNNING)
    logger.info(f"Dispatching job '{job_id}' for trials ready to be postprocessed...")
    try:
        while True:
            trials_status = db.get_job_status(job_id)["trials_status"]

            still_pending = any(
                trial_status["status"]
                in (TrialStatus.WAITING_ON_INPUT_COPY, TrialStatus.INPUT_COPIED)
                for trial_status in trials_status.values()
            )
            if not still_pending:
                logger.info(
                    f"No more trials waiting on input copy for job '{job_id}'; "
                    "dispatcher quitting."
                )
                break

            for trial_id, trial_status in trials_status.items():
                if trial_status["status"] == TrialStatus.INPUT_COPIED:
                    slurm_script_path = job_dir / trial_id / f"{trial_id}.run"
                    logger.info(
                        f"Submitting SLURM postprocessing job for trial '{trial_id}'..."
                    )
                    run(["sbatch", str(slurm_script_path)], check=True)
                    db.update_trial_status(job_id, trial_id, TrialStatus.PROCESSING_QUEUED)

            time.sleep(poll_interval_seconds)
    except Exception as e:
        logger.error(f"Dispatcher for job '{job_id}' failed: {e}")
        db.update_dispatcher_status(job_id, DispatcherStatus.FAILED, error=str(e))
        raise

    db.update_dispatcher_status(job_id, DispatcherStatus.COMPLETE)


def main() -> None:
    tyro.cli(spotlight_job_dispatcher)


if __name__ == "__main__":
    main()
