import time
from datetime import datetime, timezone
from pathlib import Path

import tyro
from loguru import logger

import spotlight_postprocessing_scitas.common.config as config
from spotlight_postprocessing_scitas.common import slurm
from spotlight_postprocessing_scitas.common.db import (
    DISPATCHER_ACTIVE_TRIAL_STATUSES,
    TERMINAL_TRIAL_STATUSES,
    DispatcherStatus,
    JobsDatabase,
    JobStatus,
    TrialStatus,
)


def spotlight_job_dispatcher(job_id: str, poll_interval_seconds: float = 15.0) -> None:
    """Watch a postprocessing job in Firestore for its entire lifetime, dispatching
    each trial's pre-generated SLURM postprocessing job as soon as its input data has
    finished copying, and cross-checking every dispatched trial's SLURM state so a
    trial whose job gets killed outright (OOM, walltime, node failure, ...) is still
    marked `FAILED` instead of being stuck forever.

    Runs on a SCITAS compute node (launched by `launch_dispatcher`, which also
    pre-generates every trial's task manifest and SLURM batch script, since the job's
    trials and parameters are already known from Firestore at that point). This
    dispatcher is assumed to be the one component in the pipeline that cannot die: it
    is also responsible for detecting a dead client-side submission program (via its
    Firestore heartbeat) and, if so, cancelling every trial's SLURM job and marking
    the whole job `FAILED`. As a last resort, if this dispatcher itself crashes on an
    unexpected exception, it still marks the job and every unfinished trial `FAILED`
    before re-raising, rather than leaving them stuck in `PROCESSING` forever with
    nothing left watching them.

    Does not quit until every trial has reached a terminal status (`OUTPUT_READY` or
    `FAILED`), or the job is aborted due to a dead client.

    This dispatcher's own status (`RUNNING`, then `COMPLETE` or `FAILED`) is recorded
    in Firestore under the job's `dispatcher` field, alongside the SLURM job ID
    recorded by `launch_dispatcher`.

    Args:
        job_id: ID of the job (as generated by `submit_remote_postprocessing_job`) to
            dispatch.
        poll_interval_seconds: How often, in seconds, to poll Firestore (and, for
            already-dispatched trials, `sacct`) for status updates.
    """
    db = JobsDatabase(config.FIRESTORE_SERVICE_ACCOUNT_KEY_PATH)
    job_dir = (
        config.SCITAS_EXPORT_MOUNTPOINT_SCITAS / config.SCITAS_EXPORT_RELATIVE_WORKDIR
    ).resolve() / job_id

    db.update_dispatcher_status(job_id, DispatcherStatus.RUNNING)
    logger.info(f"Dispatching job '{job_id}' until all trials are ready or failed...")
    try:
        while True:
            job_status = db.get_job_status(job_id)
            trials = job_status["trials"]

            if _client_heartbeat_stale(job_status.get("client_heartbeat")):
                _abort_job_due_to_dead_client(db, job_id, trials)
                return

            unsettled = {
                trial_id: trial
                for trial_id, trial in trials.items()
                if trial["status"] in DISPATCHER_ACTIVE_TRIAL_STATUSES
            }
            if not unsettled:
                logger.info(
                    f"All trials for job '{job_id}' are ready or failed; dispatcher "
                    "quitting."
                )
                break

            for trial_id, trial in unsettled.items():
                try:
                    if trial["status"] == TrialStatus.INPUT_COPIED:
                        _submit_trial_job(db, job_dir, job_id, trial_id)
                    elif trial["status"] in (
                        TrialStatus.PROCESSING_QUEUED,
                        TrialStatus.PROCESSING,
                    ):
                        _check_trial_slurm_state(db, job_id, trial_id, trial)
                except Exception as e:
                    logger.error(f"Failed to dispatch/monitor trial '{trial_id}': {e}")
                    db.update_trial_status(
                        job_id, trial_id, TrialStatus.FAILED, error=str(e)
                    )

            time.sleep(poll_interval_seconds)
    except Exception as e:
        logger.error(f"Dispatcher for job '{job_id}' failed: {e}")
        db.update_dispatcher_status(job_id, DispatcherStatus.FAILED, error=str(e))
        # This dispatcher is assumed to be the only thing left watching the job; if it
        # is dying too, don't leave the job (and any trial still in flight) stuck in
        # `PROCESSING` forever with nothing left to notice.
        db.fail_incomplete_trials(job_id, error=f"Dispatcher crashed: {e}")
        db.mark_job_complete(job_id, JobStatus.ALL_FAIL)
        raise

    db.update_dispatcher_status(job_id, DispatcherStatus.COMPLETE)


def _submit_trial_job(
    db: JobsDatabase, job_dir: Path, job_id: str, trial_id: str
) -> None:
    slurm_script_path = job_dir / trial_id / f"{trial_id}.run"
    logger.info(f"Submitting SLURM postprocessing job for trial '{trial_id}'...")
    slurm_job_id = slurm.submit_job(slurm_script_path)
    db.set_trial_slurm_job_id(job_id, trial_id, slurm_job_id)
    db.update_trial_status(job_id, trial_id, TrialStatus.PROCESSING_QUEUED)


def _check_trial_slurm_state(
    db: JobsDatabase, job_id: str, trial_id: str, trial: dict
) -> None:
    """Cross-check a dispatched trial's SLURM job state directly against `sacct`, and
    mark it `FAILED` if SLURM reports the job has ended without the trial ever
    reporting a final status itself (i.e. it was killed outright: OOM, walltime, node
    failure, etc., rather than failing through its own exception handling)."""
    slurm_job_id = trial.get("slurm_job_id")
    if not slurm_job_id:
        return
    state = slurm.get_job_state(slurm_job_id)
    if state is None or state in slurm.ACTIVE_STATES:
        return

    # `sacct` is comparatively slow, and is queried once per unsettled trial per poll;
    # by the time we get here the trial may already have reported its own final status
    # (it was marked `PROCESSING`/`PROCESSING_QUEUED` in the snapshot fetched at the
    # top of this poll, but that can be several seconds stale by now). Re-check its
    # live status so a trial that actually finished isn't overwritten with `FAILED`.
    live_status = TrialStatus(db.get_job(job_id)["trials"][trial_id]["status"])
    if live_status not in DISPATCHER_ACTIVE_TRIAL_STATUSES:
        return

    logger.error(
        f"Trial '{trial_id}' SLURM job {slurm_job_id} ended with state '{state}' "
        "without reporting a final status; marking failed."
    )
    db.update_trial_status(
        job_id,
        trial_id,
        TrialStatus.FAILED,
        error=(
            f"SLURM job {slurm_job_id} ended with state '{state}' without the trial "
            "reporting a final status (likely killed outright: OOM, walltime, node "
            "failure, etc.)."
        ),
    )


def _client_heartbeat_stale(client_heartbeat) -> bool:
    if client_heartbeat is None:
        return False
    age_seconds = (datetime.now(timezone.utc) - client_heartbeat).total_seconds()
    return age_seconds > config.CLIENT_HEARTBEAT_TIMEOUT


def _abort_job_due_to_dead_client(db: JobsDatabase, job_id: str, trials: dict) -> None:
    """Cancel every trial's SLURM job (if any) and mark the whole job `ALL_FAIL`,
    because the client-side submission program has stopped sending heartbeats.

    Every trial not already terminal is marked `FAILED` -- not just the ones the
    dispatcher itself dispatched (`DISPATCHER_ACTIVE_TRIAL_STATUSES`), since a trial
    stuck mid-output-copy on the (now-dead) client would otherwise be left forever in
    `OUTPUT_READY`/`OUTPUT_COPYING` with nothing watching it.
    """
    logger.error(
        f"Client heartbeat for job '{job_id}' timed out; aborting the job and "
        "cancelling all its SLURM jobs."
    )
    for trial_id, trial in trials.items():
        if trial["status"] in TERMINAL_TRIAL_STATUSES:
            continue
        slurm_job_id = trial.get("slurm_job_id")
        if slurm_job_id:
            slurm.cancel_job(slurm_job_id)
        db.update_trial_status(
            job_id,
            trial_id,
            TrialStatus.FAILED,
            error="Aborted: client-side submission program stopped sending "
            "heartbeats (assumed dead).",
        )
    db.update_dispatcher_status(
        job_id,
        DispatcherStatus.FAILED,
        error="Client-side submission program died (heartbeat timeout); job aborted.",
    )
    db.mark_job_complete(job_id, JobStatus.ALL_FAIL)


def main() -> None:
    tyro.cli(spotlight_job_dispatcher)


if __name__ == "__main__":
    main()
