import json
import re
from pathlib import Path
from string import Template
from subprocess import run

import tyro

import spotlight_postprocessing_scitas.common.config as config
from spotlight_postprocessing_scitas.common.db import JobsDatabase

_SBATCH_JOB_ID_RE = re.compile(r"Submitted batch job (\d+)")

_DISPATCHER_SLURM_TEMPLATE = Template("""#!/bin/bash -l

#SBATCH --job-name dispatcher_${job_id}
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --mem ${mem}
#SBATCH --time ${walltime}
#SBATCH --partition=standard
#SBATCH --qos=serial
#SBATCH --output ${log_file}

echo "Launching Spotlight postprocessing job dispatcher from $$(hostname) at $$(date)"

source ${spotlight_dir}/tools/.venv/bin/activate
spotlight-job-dispatcher --job-id ${job_id}

echo "All postprocessing jobs started. Job dispatcher quitting at $$(date)"
""")


_POSTPROCESSING_SLURM_TEMPLATE = Template("""#!/bin/bash -l

#SBATCH --job-name postprocess_${trial_id}
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task ${n_cores_per_job}
#SBATCH --mem ${mem_per_job}
#SBATCH --time ${walltime}
#SBATCH --partition=${partition}
#SBATCH --qos=serial
#SBATCH --output ${log_file}

echo "Launching postprocessing job for trial ${trial_id} from $$(hostname) at $$(date)"

source ${spotlight_dir}/tools/.venv/bin/activate
remote-postprocess-recording --from-json ${task_json_path}

echo "Postprocessing job for trial ${trial_id} completed at $$(date)"
""")


def launch_dispatcher(job_id: str) -> None:
    """Submit a SLURM job on SCITAS that dispatches a postprocessing job.

    Since the job's trials, `scitas_params`, and `postprocessing_params` are already
    known from Firestore at this point, this pre-generates the task manifest and SLURM
    batch script for every trial in the job right away. The dispatcher (run via the
    `spotlight-job-dispatcher` entry point, launched by the generated SLURM script)
    then only has to `sbatch` each trial's pre-generated script as soon as its input
    data becomes available under the job's SCITAS export directory, and report trial
    statuses back to Firestore. The dispatcher SLURM job's own ID and status are also
    recorded in Firestore, under the job's `dispatcher` field.

    Args:
        job_id: ID of the job (as generated by `submit_remote_postprocessing_job`)
            to dispatch.
    """
    db = JobsDatabase(config.FIRESTORE_SERVICE_ACCOUNT_KEY_PATH)
    job = db.get_job(job_id)
    scitas_params = job["scitas_params"]
    postprocessing_params = job["postprocessing_params"]

    job_dir = (
        config.SCITAS_EXPORT_MOUNTPOINT_SCITAS / config.SCITAS_EXPORT_RELATIVE_WORKDIR
    ).resolve() / job_id
    batch_scripts_dir = job_dir / "slurm_scripts"
    logs_dir = job_dir / "logs"
    batch_scripts_dir.mkdir(parents=True, exist_ok=True)
    logs_dir.mkdir(parents=True, exist_ok=True)

    # Pre-generate each trial's task manifest and SLURM batch script. The dispatcher
    # just submits these via `sbatch` once each trial's input data has been copied
    for trial_id in job["trials"]:
        _write_postprocessing_batch_script(
            job_dir, job_id, trial_id, scitas_params, postprocessing_params
        )

    # Start dispatcher job
    dispatcher_batch_script_path = batch_scripts_dir / "dispatcher.slurm"
    _write_dispatcher_batch_script(job_id, dispatcher_batch_script_path, logs_dir)
    result = run(
        ["sbatch", str(dispatcher_batch_script_path)],
        check=True,
        capture_output=True,
        text=True,
    )
    slurm_job_id = _parse_sbatch_job_id(result.stdout)
    db.set_dispatcher_slurm_job_id(job_id, slurm_job_id)


def _parse_sbatch_job_id(sbatch_stdout: str) -> str:
    match = _SBATCH_JOB_ID_RE.search(sbatch_stdout)
    if not match:
        raise ValueError(f"Could not parse SLURM job ID from `sbatch` output: {sbatch_stdout!r}")
    return match.group(1)


def _write_dispatcher_batch_script(
    job_id: str, batch_script_path: Path, logs_dir: Path
):
    batch_script_path.write_text(
        _DISPATCHER_SLURM_TEMPLATE.substitute(
            job_id=job_id,
            mem=config.SCITAS_DISPATCHER_MEMORY,
            walltime=config.SCITAS_DISPATCHER_WALLTIME,
            spotlight_dir=config.SCITAS_SPOTLIGHT_REPO_DIR,
            log_file=logs_dir / "dispatcher.log",
        )
    )


def _write_postprocessing_batch_script(
    job_dir: Path,
    job_id: str,
    trial_id: str,
    scitas_params: dict,
    postprocessing_params: dict,
) -> None:
    """Pre-generate the task manifest and SLURM batch script for one trial's
    postprocessing job. The dispatcher submits this script via `sbatch` once the
    trial's input data has finished copying."""
    trial_dir = job_dir / trial_id
    trial_dir.mkdir(parents=True, exist_ok=True)
    task_json_path = trial_dir / "task.json"
    slurm_script_path = job_dir / "slurm_scripts" / f"{trial_id}.slurm"
    log_file = job_dir / "logs" / f"{trial_id}.log"

    task_json_path.write_text(
        json.dumps(
            {
                "job_id": job_id,
                "trial_id": trial_id,
                "trial_dir": str(trial_dir),
                "postprocessing_params": postprocessing_params,
            },
            indent=4,
        )
    )
    slurm_script_path.write_text(
        _POSTPROCESSING_SLURM_TEMPLATE.substitute(
            trial_id=trial_id,
            n_cores_per_job=scitas_params["n_cores_per_job"],
            mem_per_job=scitas_params["mem_per_job"],
            walltime=scitas_params["walltime"],
            partition=scitas_params["partition"],
            log_file=log_file,
            spotlight_dir=config.SCITAS_SPOTLIGHT_REPO_DIR,
            task_json_path=task_json_path,
        )
    )


def main() -> None:
    tyro.cli(launch_dispatcher)


if __name__ == "__main__":
    main()
