"""
Modified from code generated by Claude 3.7 Sonnet
"""

import cv2
import numpy as np
from pathlib import Path

from calibration.aruco import detect_aruco_markers


def process_image(input_image_path, output_image_path, flip_horizontal):
    """
    Processes an image file to detect ArUco markers, saves visualization,
    and prints the results.

    Args:
        input_image_path (str): Path to the input image
        output_image_path (str): Path to save the output image with detected
            markers
        flip_horizontal (bool): Whether to flip the image horizontally before
            processing. This is needed because the camera is looking from the
            bottom up, but the ArUco markers are defined with +x as "toward
            the right" from above.

    Returns:
        tuple: (marker_ids, corner_locations)
    """
    try:
        # Read the input image
        image = cv2.imread(str(input_image_path))

        # Flip the image horizontally if needed
        if flip_horizontal:
            image = cv2.flip(image, 1)
        
        # Convert to grayscale
        if len(image.shape) == 3:
            image = image[:, :, 0]
        
        # Detect ArUco markers
        marker_ids, corner_locations = detect_aruco_markers(image)
        
        # Unflip image and labels if needed
        if flip_horizontal:
            image = cv2.flip(image, 1)
            for corner_points in corner_locations:
                for point in corner_points:
                    point[0] = image.shape[1] - point[0]

        # Get total number of markers detected
        total_markers = 0 if marker_ids is None else len(marker_ids)

        # Visualization
        if total_markers > 0:
            # Convert corner_locations back to the format expected by
            # drawDetectedMarkers
            corners_for_drawing = [
                np.array([cl], dtype=np.float32) for cl in corner_locations
            ]

            # Draw detected markers on a copy of the image for visualization
            image_with_markers = cv2.cvtColor(image, cv2.COLOR_GRAY2RGB)
            cv2.aruco.drawDetectedMarkers(
                image_with_markers, corners_for_drawing, marker_ids
            )
            cv2.imwrite(str(output_image_path), image_with_markers)

        # Display results
        print(f"Total ArUco markers detected: {total_markers}")

        if total_markers > 0:
            print("\nArUco marker details:")
            for i in range(total_markers):
                marker_id = marker_ids[i][0]
                print(f"\nMarker ID: {marker_id}")
                print("Corner locations (x, y):")
                for j, point in enumerate(corner_locations[i]):
                    corner_name = [
                        "Top-Left",
                        "Top-Right",
                        "Bottom-Right",
                        "Bottom-Left",
                    ][j]
                    print(f"  {corner_name}: ({point[0]:.1f}, {point[1]:.1f})")

        return marker_ids, corner_locations

    except Exception as e:
        print(f"Error: {e}")
        return None, []


if __name__ == "__main__":
    base_dir = Path("./data/aruco_detection_examples")
    base_dir.mkdir(parents=True, exist_ok=True)

    process_image(
        base_dir / "sample_aruco_image_0.3mm_24x22.jpg",
        base_dir / "sample_aruco_image_0.3mm_24x22_detected.jpg",
        flip_horizontal=False,
    )

    print("*" * 80)

    process_image(
        base_dir / "sample_aruco_image_0.4mm_25x17.jpg",
        base_dir / "sample_aruco_image_0.4mm_25x17_detected.jpg",
        flip_horizontal=False,
    )

    print("*" * 80)

    process_image(
        "/home/spotlight/Spotlight/calibration/aruco_scan/behavior_images/behavior_frame_000000024.jpg",
        base_dir / "test_from_real_scan.jpg",
        flip_horizontal=True,
    )
