"""NeuroMechFly body-plan loading, SLEAP<->joint name mapping, and the
actual QuickIK 2D-keypoint IK/FK solve.

The body-plan JSON (`spotlight.get_assets_dir() /
"inverse_kinematics/neuromechfly_ypr_legs.json"`) is generated by
`../flygym/scripts/export_model_for_quickik.py`; see `scripts/postprocessing/
README.md` for the exact command. Its 31 joints double as keypoints: the
root "thorax", plus per leg (`lf`, `lm`, `lh`, `rf`, `rm`, `rh`)
`{leg}_thorax_coxa`, `{leg}_coxa_trochanterfemur`,
`{leg}_trochanterfemur_tibia`, `{leg}_tibia_tarsus`, `{leg}_claw`. Only 31 of
this project's 37 SLEAP nodes have a corresponding joint (30 leg nodes plus
"Th" -> "thorax"); the other 6 ("N", "A", "LA", "RA", "LW", "RW") don't.
"""

import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import quickik

# Swept 0.01 (QuickIK's own NeuroMechFly example, 10x its library default)
# through 0.5 against this project's rendered 3D reconstructions (mismatch
# rejection off, so a bad fit shows up instead of being dropped): 0.5/0.25
# stay stable and plausible throughout; 0.1 shows occasional single-frame
# outliers; 0.05 bends a mid-leg unrealistically in every frame; 0.01
# collapses into tangled poses (the underconstrained-observation failure
# mode QuickIK's own docs warn about). 0.2 is tighter than 0.25 while
# staying clear of the 0.1 cutoff.
NEUTRAL_WEIGHT = 0.2

# Base observation weight per body-plan joint (before `solve_period_ik`'s
# own per-frame missing-data zeroing): joints closer to the free-floating
# root are more entangled with root-pose ambiguity than distal ones, so
# they're trusted less as independent observations. Midleg ThC is trusted
# least of the four ThC joints.
MIDLEG_THC_WEIGHT = 0.25
FRONT_HIND_THC_WEIGHT = 0.5
CTR_WEIGHT = 0.75
DISTAL_WEIGHT = 1.0  # FTi, TiTa, claw

MID_LEG_PREFIXES = {"lm", "rm"}

LEG_PREFIX_MAP = {
    "LF": "lf",
    "LM": "lm",
    "LH": "lh",
    "RF": "rf",
    "RM": "rm",
    "RH": "rh",
}
LEG_JOINT_MAP = {
    "ThC": "thorax_coxa",
    "CTr": "coxa_trochanterfemur",
    "FTi": "trochanterfemur_tibia",
    "TiTa": "tibia_tarsus",
    "Cl": "claw",
}


@dataclass
class BodyPlan:
    """A loaded NeuroMechFly body plan: the `KinematicTree` plus its name orders."""

    tree: quickik.KinematicTree
    joint_names: list[str]
    """Joint names, in `tree`'s own joint order."""
    dof_names: list[str]
    """DOF names, in each `SolverResult.dof_angles`' order."""

    @classmethod
    def load(cls, body_plan_path: Path) -> "BodyPlan":
        """Load a body-plan JSON as a `BodyPlan`.

        Args:
            body_plan_path: Path to the body-plan JSON (see
                `flygym/scripts/export_model_for_quickik.py`).
        """
        with open(body_plan_path) as f:
            body_plan = json.load(f)
        joint_names = [joint["name"] for joint in body_plan["joints"]]
        dof_names = [
            dof["name"] for joint in body_plan["joints"] for dof in joint["dofs"]
        ]
        tree = quickik.KinematicTree.from_json_file(str(body_plan_path))
        return cls(tree=tree, joint_names=joint_names, dof_names=dof_names)


def build_sleap_to_joint_name_map() -> dict[str, str]:
    """Map SLEAP node names to NeuroMechFly body-plan joint names.

    Returns:
        Dict from SLEAP node name to body-plan joint name, for every SLEAP
        node that has a corresponding joint (30 leg nodes plus "Th" ->
        "thorax"). The other 6 SLEAP nodes ("N", "A", "LA", "RA", "LW",
        "RW") have no corresponding joint and are absent from the returned
        dict.
    """
    mapping = {"Th": "thorax"}
    for sleap_prefix, joint_prefix in LEG_PREFIX_MAP.items():
        for sleap_joint, joint_suffix in LEG_JOINT_MAP.items():
            mapping[f"{sleap_prefix}_{sleap_joint}"] = f"{joint_prefix}_{joint_suffix}"
    return mapping


def base_observation_weight(joint_name: str) -> float:
    """Base observation weight for one body-plan joint, before
    `solve_period_ik`'s own per-frame missing-data zeroing.

    Args:
        joint_name: A `BodyPlan.joint_names` entry, e.g. `"lf_thorax_coxa"`
            or the root `"thorax"`.

    Returns:
        `0.0` for the root ("thorax"; never a valid observation, see
        `solve_period_ik`); `MIDLEG_THC_WEIGHT`/`FRONT_HIND_THC_WEIGHT` for
        a ThC joint, depending on which leg it belongs to; `CTR_WEIGHT` for
        a CTr joint; `DISTAL_WEIGHT` for FTi/TiTa/claw.
    """
    if joint_name == "thorax":
        return 0.0
    leg_prefix, joint_type = joint_name.split("_", 1)
    if joint_type == "thorax_coxa":
        is_midleg = leg_prefix in MID_LEG_PREFIXES
        return MIDLEG_THC_WEIGHT if is_midleg else FRONT_HIND_THC_WEIGHT
    if joint_type == "coxa_trochanterfemur":
        return CTR_WEIGHT
    return DISTAL_WEIGHT  # trochanterfemur_tibia, tibia_tarsus, claw


def sleap_keypoint_weight_scale() -> dict[str, float]:
    """`base_observation_weight`, keyed by SLEAP node name instead of
    body-plan joint name, for recording alongside a solve's own results
    (see `kinematics.h5`'s `inverse_kinematics/` attrs). Excludes "Th": it
    was never a real observation to begin with (see `solve_period_ik`), so
    it has no meaningful weight to report here.
    """
    return {
        sleap_name: base_observation_weight(joint_name)
        for sleap_name, joint_name in build_sleap_to_joint_name_map().items()
        if joint_name != "thorax"
    }


def reorder_to_joint_order(
    sleap_points: np.ndarray, sleap_node_names: list[str], joint_names: list[str]
) -> np.ndarray:
    """Reorder SLEAP-order keypoints into `KinematicTree` joint order.

    Args:
        sleap_points: `(..., n_sleap_nodes, d)` array, in `sleap_node_names`
            order.
        sleap_node_names: SLEAP node names, matching `sleap_points`'s node axis.
        joint_names: Body-plan joint names, in `KinematicTree` order.

    Returns:
        `(..., len(joint_names), d)` array.
    """
    joint_to_sleap = {v: k for k, v in build_sleap_to_joint_name_map().items()}
    sleap_idx = {name: i for i, name in enumerate(sleap_node_names)}
    joint_idxs = [sleap_idx[joint_to_sleap[name]] for name in joint_names]
    return sleap_points[..., joint_idxs, :]


def reorder_from_joint_order(
    joint_points: np.ndarray, joint_names: list[str], sleap_node_names: list[str]
) -> np.ndarray:
    """Inverse of `reorder_to_joint_order`.

    Scatters joint-order keypoints back into full SLEAP node order, filling
    the 6 SLEAP nodes with no body-plan joint with NaN.

    Args:
        joint_points: `(..., len(joint_names), d)` array, in `joint_names` order.
        joint_names: Body-plan joint names, in `KinematicTree` order.
        sleap_node_names: Full SLEAP node name order to scatter into.

    Returns:
        `(..., len(sleap_node_names), d)` array.
    """
    joint_to_sleap = {v: k for k, v in build_sleap_to_joint_name_map().items()}
    sleap_idx = {name: i for i, name in enumerate(sleap_node_names)}

    out_shape = (
        *joint_points.shape[:-2],
        len(sleap_node_names),
        joint_points.shape[-1],
    )
    out = np.full(out_shape, np.nan, dtype=joint_points.dtype)
    for i, name in enumerate(joint_names):
        out[..., sleap_idx[joint_to_sleap[name]], :] = joint_points[..., i, :]
    return out


def solve_period_ik(
    pred_2d_mm: np.ndarray,
    node_names: list[str],
    body_plan: BodyPlan,
    neutral_weight: float = NEUTRAL_WEIGHT,
) -> tuple[np.ndarray, np.ndarray]:
    """Fit IK to one period's 2D (mm) keypoint sequence.

    Builds a fresh `quickik.SequenceSolver` for this call rather than
    reusing one across periods: `SequenceSolver` warm-starts every frame
    from wherever its own last `solve` call left off, and periods are
    separated by a run of rejected frames, so reusing one across periods
    would warm-start a period's first frame from an unrelated prior period's
    last one.

    Args:
        pred_2d_mm: `(period_length, n_sleap_nodes, 2)` physical (mm)
            keypoints, may contain NaN.
        node_names: SLEAP node names, matching `pred_2d_mm`'s node axis.
        body_plan: See `BodyPlan.load`.
        neutral_weight: `SequenceSolver`'s prior weight pulling the solution
            toward the body plan's neutral pose (see `NEUTRAL_WEIGHT`'s
            comment for how the default was chosen).

    Returns:
        dof_angles: `(period_length, n_dofs)` solved joint angles, radians.
        fk_3d_mm: `(period_length, n_sleap_nodes, 3)` forward-kinematics
            result at the converged pose, in full SLEAP node order (NaN for
            nodes with no corresponding body-plan joint).
    """
    joint_names = body_plan.joint_names
    positions = reorder_to_joint_order(pred_2d_mm, node_names, joint_names)
    missing = np.any(np.isnan(positions), axis=-1)
    # SLEAP's "Th" landmark and the body plan's root ("thorax") joint origin
    # are different physical points on the fly (Th is an anatomical marker;
    # the body plan's thorax origin is an internal reference for the leg
    # attachment geometry), so Th is never a valid observation for the root
    # (`base_observation_weight` returns 0.0 for it): the leg-tip
    # observations (through the kinematic chain) drive the root pose
    # entirely.
    base_weights = np.array(
        [base_observation_weight(name) for name in joint_names], dtype=np.float32
    )
    weights = np.where(missing, 0.0, base_weights[np.newaxis, :]).astype(np.float32)
    positions = np.nan_to_num(positions, nan=0.0).astype(np.float32)
    # Zero the root's own position outright too, instead of letting
    # whatever SLEAP happened to predict for "Th" flow through unused;
    # its weight above is already 0 unconditionally, but this makes "never
    # real observed data" explicit rather than incidental. QuickIK's own
    # API requires one array slot per body-plan joint (root included, see
    # `validate_position_weight_shapes` in its Rust source) regardless, so
    # this can't be dropped from the array entirely, only zeroed.
    positions[..., joint_names.index("thorax"), :] = 0.0

    seq_solver = quickik.SequenceSolver(
        body_plan.tree,
        projection=quickik.Projection.new_ortho_xy(),
        neutral_weight=neutral_weight,
    )
    results = seq_solver.solve(positions, weights, with_fk=True)

    dof_angles = np.stack([result.dof_angles for result in results]).astype(np.float32)
    fk_joint_pos = np.stack([result.keypoint_pos for result in results])
    fk_3d_mm = reorder_from_joint_order(fk_joint_pos, joint_names, node_names).astype(
        np.float32
    )
    return dof_angles, fk_3d_mm
